CKEDITOR.plugins.add('Map',
{
    init: function (editor) {
        editor.addCommand('MapDialog', new CKEDITOR.dialogCommand('MapDialog'));

        editor.ui.addButton('Map',
		{
		    label: 'Map',
		    command: 'MapDialog',
		    icon: this.path + 'images/map-pin.png'
		});

        CKEDITOR.dialog.add('MapDialog', function (editor) {
            return {
                title: 'Map Properties',
                minWidth: 400,
                minHeight: 200,
                contents:
				[
					{
					    id: 'general',
					    label: 'Settings',
					    elements:
						[
							{
							    type: 'html',
							    html: 'This dialog window lets you add a Map to your website.'
							},
							{
							    type: 'textarea',
							    id: 'iframe',
							    label: 'Paste in the HTML source generated by the mapping program',
							    validate: CKEDITOR.dialog.validate.notEmpty('You must provide the HTML from the mapping program'),
							    required: true,
							    commit: function (data) {
							        data.iframe = this.getValue();
							    }
							}
						]
					}
				],
                onOk: function () {
                    var dialog = this,
						data = {};

                    this.commitContent(data);
                    
                    editor.insertHtml(data.iframe);

                }
            };
        });
    }
});